[build]
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[dns]]
  zone = "indarchitecture.fr"

  [[dns.record]]
    name = "@"
    type = "TXT"
    value = "google-site-verification=Hg4X9xMt57diq6-Gu5CTN5i-LJXRsxACpu-Yy6QmBUs"